const STATUS_INITIATED = 'INITIATED';
const STATUS_PRO_DONE = 'PRO_DONE';
const STATUS_ACTIVE = 'ACTIVE';
const STATUS_REJECTED = 'REJECTED';
const STATUS_INACTIVE = 'INACTIVE';

export { STATUS_INITIATED, STATUS_PRO_DONE, STATUS_ACTIVE, STATUS_REJECTED, STATUS_INACTIVE };
