const VIEW_INIT = 'INIT';
const VIEW_SELLERS = 'SELLERS';
const VIEW_USERS = 'USERS';
const VIEW_ADD_USER = 'ADD_USER';
const VIEW_SETTINGS = 'SETTINGS';
const VIEW_CATEGORIES = 'CATEGORIES';
const VIEW_BRANDS = 'BRANDS';
const VIEW_BRAND = 'BRAND';
const VIEW_ADD_BRAND = 'ADD_BRAND';

export {
  VIEW_INIT,
  VIEW_SELLERS,
  VIEW_USERS,
  VIEW_ADD_USER,
  VIEW_SETTINGS,
  VIEW_CATEGORIES,
  VIEW_BRANDS,
  VIEW_BRAND,
  VIEW_ADD_BRAND
};
